### ISSUE TITLE
Add s390x support in goreleaser-cgo dockerfile.

### ISSUE THREAD

**Issue by pooja0805** [cbroglie/goreleaser-cgo#2]
We are interested in adding s390x support in goreleaser-cgo Dockerfile. To proceed further, I could not find a License or contributing guide anywhere to raise PR. Can someone please guide us?

**Comment by pooja0805** [comment]
@cbroglie Can you please take a look at this?

**Comment by cbroglie** [comment]
Sorry, no, this is isn't something I'm maintaining

**Comment by pooja0805** [comment]
Thanks for the confirmation. Closing this issue.
